#!/bin/sh

MONGO_BIN=$1
DATA_PORT=$2
NODEJS_BIN=$3
HTTP_PORT=$4

# start_db.sh <path-to-mongodb> <database-port>
./start_db.sh $MONGO_BIN/mongod $DATA_PORT &

# create_db.sh <path-to-mongo> <database-port>
./create_db.sh $MONGO_BIN/mongo $DATA_PORT

# npm install
$NODEJS_BIN/npm install

# node index.js
$NODEJS_BIN/node index.js &